import hashlib
import chromadb
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings


class VectorStoreManager:
    def __init__(self, collection_name: str = "ghost_shell_docs"):
        self.embeddings = OllamaEmbeddings(
            model="nomic-embed-text",
            base_url="http://ollama:11434"
        )

        self.chroma_client = chromadb.HttpClient(host="chromadb", port=8000)

        self.vector_store = Chroma(
            client=self.chroma_client,
            collection_name=collection_name,
            embedding_function=self.embeddings,
        )

    def add_document(self, chunks):
        """
        Adds a list of document chunks to the ChromaDB vector store using Content Hashing.
        Prevents duplication by generating deterministic IDs for each chunk.

        :param chunks: A list of document chunks generated by the text splitter.
        :type chunks: list
        :return: None
        """
        ids = []
        for chunk in chunks:
            content = chunk.page_content
            source = chunk.metadata.get("source", "unknown")

            unique_string = f"{source}::{content}"

            chunk_id = hashlib.sha256(unique_string.encode("utf-8")).hexdigest()
            ids.append(chunk_id)

        self.vector_store.add_documents(documents=chunks, ids=ids)

    def get_retriever(self, k: int = 4):
        """
        Returns a retriever interface from the vector store for semantic search.

        :param k: The number of top relevant chunks to retrieve.
        :type k: int
        :return: A LangChain retriever instance.
        """
        return self.vector_store.as_retriever(search_kwargs={"k": k})

    def get_collection_info(self):
        """
        Retrieves information about the documents currently stored in the collection.

        :return: A dictionary containing the total number of chunks and their metadata.
        """
        data = self.vector_store.get()
        return {
            "total_chunks": len(data["ids"]),
            "metadatas": data["metadatas"]
        }
